name: flutter_stetho_example
description: Demonstrates how to use the flutter_stetho plugin.

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.11.3+16 <0.12.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_stetho:
    path: ../

flutter:
  uses-material-design: true
